
---
name: justfile-exec

concurrency:
  group: run
  cancel-in-progress: true

on:
  push:
    branches:
      - "**"

jobs:
  # This job detects which parts of the repo have been changed, setting future jobs up for conditional behavior.
  justfile-exec:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run make ci-build in dev container
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: just all
      
